# export.py
# Exports answers to PDF using reportlab

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import io
from datetime import datetime


def generate_pdf(question, answer, confidence, sources=None):
    """
    Generate a PDF from a question + answer.
    Returns bytes of the PDF file.
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()

    # ── Custom Styles ──────────────────────────────────
    title_style = ParagraphStyle(
        'OracleTitle',
        parent=styles['Normal'],
        fontSize=22,
        fontName='Helvetica-Bold',
        textColor=colors.HexColor('#16a34a'),
        spaceAfter=4,
        alignment=TA_CENTER
    )

    subtitle_style = ParagraphStyle(
        'OracleSubtitle',
        parent=styles['Normal'],
        fontSize=9,
        fontName='Helvetica',
        textColor=colors.HexColor('#6b9e6b'),
        spaceAfter=16,
        alignment=TA_CENTER
    )

    label_style = ParagraphStyle(
        'OracleLabel',
        parent=styles['Normal'],
        fontSize=9,
        fontName='Helvetica-Bold',
        textColor=colors.HexColor('#16a34a'),
        spaceBefore=14,
        spaceAfter=6,
        leftIndent=0,
    )

    question_style = ParagraphStyle(
        'OracleQuestion',
        parent=styles['Normal'],
        fontSize=13,
        fontName='Helvetica-Bold',
        textColor=colors.HexColor('#1a2e1a'),
        spaceAfter=8,
        leading=18,
    )

    answer_style = ParagraphStyle(
        'OracleAnswer',
        parent=styles['Normal'],
        fontSize=11,
        fontName='Helvetica',
        textColor=colors.HexColor('#2d3d2d'),
        spaceAfter=6,
        leading=16,
    )

    meta_style = ParagraphStyle(
        'OracleMeta',
        parent=styles['Normal'],
        fontSize=9,
        fontName='Helvetica',
        textColor=colors.HexColor('#6b9e6b'),
        spaceAfter=4,
    )

    footer_style = ParagraphStyle(
        'OracleFooter',
        parent=styles['Normal'],
        fontSize=8,
        fontName='Helvetica',
        textColor=colors.HexColor('#9ca3af'),
        alignment=TA_CENTER,
        spaceBefore=20,
    )

    # ── Build Content ──────────────────────────────────
    story = []

    # Header
    story.append(Paragraph("🔭 ORACLE", title_style))
    story.append(Paragraph("AI-Powered Answer — Free · Open · Verified", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#c8e6c8'), spaceAfter=16))

    # Meta info
    now = datetime.now().strftime("%d %B %Y, %I:%M %p")
    story.append(Paragraph(f"Generated: {now}   |   Confidence: {confidence}%", meta_style))
    story.append(Spacer(1, 8))

    # Question
    story.append(Paragraph("❓ QUESTION", label_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#c8e6c8'), spaceAfter=8))
    story.append(Paragraph(question, question_style))
    story.append(Spacer(1, 12))

    # Answer
    story.append(Paragraph("💡 ANSWER", label_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#c8e6c8'), spaceAfter=8))

    # Split answer into paragraphs
    for para in answer.split('\n'):
        para = para.strip()
        if para:
            story.append(Paragraph(para, answer_style))
            story.append(Spacer(1, 4))

    # Sources
    if sources:
        story.append(Spacer(1, 12))
        story.append(Paragraph("📖 SOURCES", label_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#c8e6c8'), spaceAfter=8))
        for src in sources:
            story.append(Paragraph(f"• {src['title']} — {src['url']}", meta_style))

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#c8e6c8')))
    story.append(Paragraph("Generated by ORACLE Free AI Helper · Powered by Llama 3 + DuckDuckGo + Wikipedia", footer_style))

    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.read()
